// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class ProjectBgpState {
    /**
     * @return Whether BGP is enabled.
     * 
     */
    private Boolean enabled;
    /**
     * @return LocalASN assigned to the project.
     * 
     */
    private Integer localASN;

    private ProjectBgpState() {}
    /**
     * @return Whether BGP is enabled.
     * 
     */
    public Boolean enabled() {
        return this.enabled;
    }
    /**
     * @return LocalASN assigned to the project.
     * 
     */
    public Integer localASN() {
        return this.localASN;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ProjectBgpState defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enabled;
        private Integer localASN;
        public Builder() {}
        public Builder(ProjectBgpState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.localASN = defaults.localASN;
        }

        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("ProjectBgpState", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder localASN(Integer localASN) {
            if (localASN == null) {
              throw new MissingRequiredPropertyException("ProjectBgpState", "localASN");
            }
            this.localASN = localASN;
            return this;
        }
        public ProjectBgpState build() {
            final var _resultValue = new ProjectBgpState();
            _resultValue.enabled = enabled;
            _resultValue.localASN = localASN;
            return _resultValue;
        }
    }
}
