// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ServerPricingState {
    private String currency;
    private Double price;
    private String unit;

    private ServerPricingState() {}
    public String currency() {
        return this.currency;
    }
    public Double price() {
        return this.price;
    }
    public String unit() {
        return this.unit;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServerPricingState defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String currency;
        private Double price;
        private String unit;
        public Builder() {}
        public Builder(ServerPricingState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.currency = defaults.currency;
    	      this.price = defaults.price;
    	      this.unit = defaults.unit;
        }

        @CustomType.Setter
        public Builder currency(String currency) {
            if (currency == null) {
              throw new MissingRequiredPropertyException("ServerPricingState", "currency");
            }
            this.currency = currency;
            return this;
        }
        @CustomType.Setter
        public Builder price(Double price) {
            if (price == null) {
              throw new MissingRequiredPropertyException("ServerPricingState", "price");
            }
            this.price = price;
            return this;
        }
        @CustomType.Setter
        public Builder unit(String unit) {
            if (unit == null) {
              throw new MissingRequiredPropertyException("ServerPricingState", "unit");
            }
            this.unit = unit;
            return this;
        }
        public ServerPricingState build() {
            final var _resultValue = new ServerPricingState();
            _resultValue.currency = currency;
            _resultValue.price = price;
            _resultValue.unit = unit;
            return _resultValue;
        }
    }
}
