// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ServerIPState {
    private String address;
    private String id;
    private String type;

    private ServerIPState() {}
    public String address() {
        return this.address;
    }
    public String id() {
        return this.id;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServerIPState defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String address;
        private String id;
        private String type;
        public Builder() {}
        public Builder(ServerIPState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.address = defaults.address;
    	      this.id = defaults.id;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder address(String address) {
            if (address == null) {
              throw new MissingRequiredPropertyException("ServerIPState", "address");
            }
            this.address = address;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("ServerIPState", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("ServerIPState", "type");
            }
            this.type = type;
            return this;
        }
        public ServerIPState build() {
            final var _resultValue = new ServerIPState();
            _resultValue.address = address;
            _resultValue.id = id;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
