// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.caliban0.pulumicherryservers.Utilities;
import com.caliban0.pulumicherryservers.provider.IPArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Cherry Servers IP address.
 * 
 */
@ResourceType(type="pulumi-cherry-servers:provider:IP")
public class IP extends com.pulumi.resources.CustomResource {
    /**
     * IP address A record.
     * 
     */
    @Export(name="aRecord", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> aRecord;

    /**
     * @return IP address A record.
     * 
     */
    public Output<Optional<String>> aRecord() {
        return Codegen.optional(this.aRecord);
    }
    /**
     * Actual address.
     * 
     */
    @Export(name="address", refs={String.class}, tree="[0]")
    private Output<String> address;

    /**
     * @return Actual address.
     * 
     */
    public Output<String> address() {
        return this.address;
    }
    /**
     * IP address family.
     * 
     */
    @Export(name="addressFamily", refs={Integer.class}, tree="[0]")
    private Output<Integer> addressFamily;

    /**
     * @return IP address family.
     * 
     */
    public Output<Integer> addressFamily() {
        return this.addressFamily;
    }
    /**
     * IP address CIDR.
     * 
     */
    @Export(name="cidr", refs={String.class}, tree="[0]")
    private Output<String> cidr;

    /**
     * @return IP address CIDR.
     * 
     */
    public Output<String> cidr() {
        return this.cidr;
    }
    @Export(name="project", refs={Integer.class}, tree="[0]")
    private Output<Integer> project;

    public Output<Integer> project() {
        return this.project;
    }
    /**
     * IP address PTR record.
     * 
     */
    @Export(name="ptrRecord", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ptrRecord;

    /**
     * @return IP address PTR record.
     * 
     */
    public Output<Optional<String>> ptrRecord() {
        return Codegen.optional(this.ptrRecord);
    }
    /**
     * IP address project ID.
     * 
     */
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    /**
     * @return IP address project ID.
     * 
     */
    public Output<String> region() {
        return this.region;
    }
    /**
     * IP address that this address is routed to.
     * 
     */
    @Export(name="routedTo", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> routedTo;

    /**
     * @return IP address that this address is routed to.
     * 
     */
    public Output<Optional<String>> routedTo() {
        return Codegen.optional(this.routedTo);
    }
    /**
     * IP address tags.
     * 
     */
    @Export(name="tags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> tags;

    /**
     * @return IP address tags.
     * 
     */
    public Output<Optional<Map<String,String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * Server that this address is targeted to.
     * 
     */
    @Export(name="targetedTo", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> targetedTo;

    /**
     * @return Server that this address is targeted to.
     * 
     */
    public Output<Optional<Integer>> targetedTo() {
        return Codegen.optional(this.targetedTo);
    }
    /**
     * IP address type.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return IP address type.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IP(java.lang.String name) {
        this(name, IPArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IP(java.lang.String name, IPArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IP(java.lang.String name, IPArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:IP", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private IP(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:IP", name, null, makeResourceOptions(options, id), false);
    }

    private static IPArgs makeArgs(IPArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? IPArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static IP get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new IP(name, id, options);
    }
}
