// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IPArgs extends com.pulumi.resources.ResourceArgs {

    public static final IPArgs Empty = new IPArgs();

    /**
     * IP address A record.
     * 
     */
    @Import(name="aRecord")
    private @Nullable Output<String> aRecord;

    /**
     * @return IP address A record.
     * 
     */
    public Optional<Output<String>> aRecord() {
        return Optional.ofNullable(this.aRecord);
    }

    @Import(name="project", required=true)
    private Output<Integer> project;

    public Output<Integer> project() {
        return this.project;
    }

    /**
     * IP address PTR record.
     * 
     */
    @Import(name="ptrRecord")
    private @Nullable Output<String> ptrRecord;

    /**
     * @return IP address PTR record.
     * 
     */
    public Optional<Output<String>> ptrRecord() {
        return Optional.ofNullable(this.ptrRecord);
    }

    /**
     * IP address project ID.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return IP address project ID.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    /**
     * IP address that this address is routed to.
     * 
     */
    @Import(name="routedTo")
    private @Nullable Output<String> routedTo;

    /**
     * @return IP address that this address is routed to.
     * 
     */
    public Optional<Output<String>> routedTo() {
        return Optional.ofNullable(this.routedTo);
    }

    /**
     * IP address tags.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<Map<String,String>> tags;

    /**
     * @return IP address tags.
     * 
     */
    public Optional<Output<Map<String,String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    /**
     * Server that this address is targeted to.
     * 
     */
    @Import(name="targetedTo")
    private @Nullable Output<Integer> targetedTo;

    /**
     * @return Server that this address is targeted to.
     * 
     */
    public Optional<Output<Integer>> targetedTo() {
        return Optional.ofNullable(this.targetedTo);
    }

    private IPArgs() {}

    private IPArgs(IPArgs $) {
        this.aRecord = $.aRecord;
        this.project = $.project;
        this.ptrRecord = $.ptrRecord;
        this.region = $.region;
        this.routedTo = $.routedTo;
        this.tags = $.tags;
        this.targetedTo = $.targetedTo;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IPArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IPArgs $;

        public Builder() {
            $ = new IPArgs();
        }

        public Builder(IPArgs defaults) {
            $ = new IPArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param aRecord IP address A record.
         * 
         * @return builder
         * 
         */
        public Builder aRecord(@Nullable Output<String> aRecord) {
            $.aRecord = aRecord;
            return this;
        }

        /**
         * @param aRecord IP address A record.
         * 
         * @return builder
         * 
         */
        public Builder aRecord(String aRecord) {
            return aRecord(Output.of(aRecord));
        }

        public Builder project(Output<Integer> project) {
            $.project = project;
            return this;
        }

        public Builder project(Integer project) {
            return project(Output.of(project));
        }

        /**
         * @param ptrRecord IP address PTR record.
         * 
         * @return builder
         * 
         */
        public Builder ptrRecord(@Nullable Output<String> ptrRecord) {
            $.ptrRecord = ptrRecord;
            return this;
        }

        /**
         * @param ptrRecord IP address PTR record.
         * 
         * @return builder
         * 
         */
        public Builder ptrRecord(String ptrRecord) {
            return ptrRecord(Output.of(ptrRecord));
        }

        /**
         * @param region IP address project ID.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region IP address project ID.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param routedTo IP address that this address is routed to.
         * 
         * @return builder
         * 
         */
        public Builder routedTo(@Nullable Output<String> routedTo) {
            $.routedTo = routedTo;
            return this;
        }

        /**
         * @param routedTo IP address that this address is routed to.
         * 
         * @return builder
         * 
         */
        public Builder routedTo(String routedTo) {
            return routedTo(Output.of(routedTo));
        }

        /**
         * @param tags IP address tags.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<Map<String,String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags IP address tags.
         * 
         * @return builder
         * 
         */
        public Builder tags(Map<String,String> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param targetedTo Server that this address is targeted to.
         * 
         * @return builder
         * 
         */
        public Builder targetedTo(@Nullable Output<Integer> targetedTo) {
            $.targetedTo = targetedTo;
            return this;
        }

        /**
         * @param targetedTo Server that this address is targeted to.
         * 
         * @return builder
         * 
         */
        public Builder targetedTo(Integer targetedTo) {
            return targetedTo(Output.of(targetedTo));
        }

        public IPArgs build() {
            if ($.project == null) {
                throw new MissingRequiredPropertyException("IPArgs", "project");
            }
            if ($.region == null) {
                throw new MissingRequiredPropertyException("IPArgs", "region");
            }
            return $;
        }
    }

}
