// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.caliban0.pulumicherryservers.Utilities;
import com.caliban0.pulumicherryservers.provider.ProjectArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Cherry Servers project.
 * 
 */
@ResourceType(type="pulumi-cherry-servers:provider:Project")
public class Project extends com.pulumi.resources.CustomResource {
    /**
     * Whether BGP should be enabled for the project.
     * 
     */
    @Export(name="bgp", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> bgp;

    /**
     * @return Whether BGP should be enabled for the project.
     * 
     */
    public Output<Optional<Boolean>> bgp() {
        return Codegen.optional(this.bgp);
    }
    /**
     * LocalASN assigned to the project.
     * 
     */
    @Export(name="localASN", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> localASN;

    /**
     * @return LocalASN assigned to the project.
     * 
     */
    public Output<Optional<Integer>> localASN() {
        return Codegen.optional(this.localASN);
    }
    /**
     * Project name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> name;

    /**
     * @return Project name.
     * 
     */
    public Output<Optional<String>> name() {
        return Codegen.optional(this.name);
    }
    /**
     * ID of the team the project belongs to.
     * 
     */
    @Export(name="team", refs={Integer.class}, tree="[0]")
    private Output<Integer> team;

    /**
     * @return ID of the team the project belongs to.
     * 
     */
    public Output<Integer> team() {
        return this.team;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Project(java.lang.String name) {
        this(name, ProjectArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Project(java.lang.String name, ProjectArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Project(java.lang.String name, ProjectArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:Project", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Project(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:Project", name, null, makeResourceOptions(options, id), false);
    }

    private static ProjectArgs makeArgs(ProjectArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProjectArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Project get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Project(name, id, options);
    }
}
