// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectArgs Empty = new ProjectArgs();

    /**
     * Whether BGP should be enabled for the project.
     * 
     */
    @Import(name="bgp")
    private @Nullable Output<Boolean> bgp;

    /**
     * @return Whether BGP should be enabled for the project.
     * 
     */
    public Optional<Output<Boolean>> bgp() {
        return Optional.ofNullable(this.bgp);
    }

    /**
     * Project name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Project name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * ID of the team the project belongs to.
     * 
     */
    @Import(name="team", required=true)
    private Output<Integer> team;

    /**
     * @return ID of the team the project belongs to.
     * 
     */
    public Output<Integer> team() {
        return this.team;
    }

    private ProjectArgs() {}

    private ProjectArgs(ProjectArgs $) {
        this.bgp = $.bgp;
        this.name = $.name;
        this.team = $.team;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectArgs $;

        public Builder() {
            $ = new ProjectArgs();
        }

        public Builder(ProjectArgs defaults) {
            $ = new ProjectArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bgp Whether BGP should be enabled for the project.
         * 
         * @return builder
         * 
         */
        public Builder bgp(@Nullable Output<Boolean> bgp) {
            $.bgp = bgp;
            return this;
        }

        /**
         * @param bgp Whether BGP should be enabled for the project.
         * 
         * @return builder
         * 
         */
        public Builder bgp(Boolean bgp) {
            return bgp(Output.of(bgp));
        }

        /**
         * @param name Project name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Project name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param team ID of the team the project belongs to.
         * 
         * @return builder
         * 
         */
        public Builder team(Output<Integer> team) {
            $.team = team;
            return this;
        }

        /**
         * @param team ID of the team the project belongs to.
         * 
         * @return builder
         * 
         */
        public Builder team(Integer team) {
            return team(Output.of(team));
        }

        public ProjectArgs build() {
            if ($.team == null) {
                throw new MissingRequiredPropertyException("ProjectArgs", "team");
            }
            return $;
        }
    }

}
