// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectArgs Empty = new ProjectArgs();

    @Import(name="bgp")
    private @Nullable Output<Boolean> bgp;

    public Optional<Output<Boolean>> bgp() {
        return Optional.ofNullable(this.bgp);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="team", required=true)
    private Output<Integer> team;

    public Output<Integer> team() {
        return this.team;
    }

    private ProjectArgs() {}

    private ProjectArgs(ProjectArgs $) {
        this.bgp = $.bgp;
        this.name = $.name;
        this.team = $.team;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectArgs $;

        public Builder() {
            $ = new ProjectArgs();
        }

        public Builder(ProjectArgs defaults) {
            $ = new ProjectArgs(Objects.requireNonNull(defaults));
        }

        public Builder bgp(@Nullable Output<Boolean> bgp) {
            $.bgp = bgp;
            return this;
        }

        public Builder bgp(Boolean bgp) {
            return bgp(Output.of(bgp));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder team(Output<Integer> team) {
            $.team = team;
            return this;
        }

        public Builder team(Integer team) {
            return team(Output.of(team));
        }

        public ProjectArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ProjectArgs", "name");
            }
            if ($.team == null) {
                throw new MissingRequiredPropertyException("ProjectArgs", "team");
            }
            return $;
        }
    }

}
