// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RandomSaltArgs extends com.pulumi.resources.ResourceArgs {

    public static final RandomSaltArgs Empty = new RandomSaltArgs();

    @Import(name="password", required=true)
    private Output<String> password;

    public Output<String> password() {
        return this.password;
    }

    @Import(name="saltedLength")
    private @Nullable Output<Integer> saltedLength;

    public Optional<Output<Integer>> saltedLength() {
        return Optional.ofNullable(this.saltedLength);
    }

    private RandomSaltArgs() {}

    private RandomSaltArgs(RandomSaltArgs $) {
        this.password = $.password;
        this.saltedLength = $.saltedLength;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RandomSaltArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RandomSaltArgs $;

        public Builder() {
            $ = new RandomSaltArgs();
        }

        public Builder(RandomSaltArgs defaults) {
            $ = new RandomSaltArgs(Objects.requireNonNull(defaults));
        }

        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        public Builder password(String password) {
            return password(Output.of(password));
        }

        public Builder saltedLength(@Nullable Output<Integer> saltedLength) {
            $.saltedLength = saltedLength;
            return this;
        }

        public Builder saltedLength(Integer saltedLength) {
            return saltedLength(Output.of(saltedLength));
        }

        public RandomSaltArgs build() {
            if ($.password == null) {
                throw new MissingRequiredPropertyException("RandomSaltArgs", "password");
            }
            return $;
        }
    }

}
