// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.caliban0.pulumicherryservers.Utilities;
import com.caliban0.pulumicherryservers.provider.RandomSaltArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="pulumi-cherry-servers:provider:RandomSalt")
public class RandomSalt extends com.pulumi.resources.CustomResource {
    @Export(name="password", refs={String.class}, tree="[0]")
    private Output<String> password;

    public Output<String> password() {
        return this.password;
    }
    @Export(name="salt", refs={String.class}, tree="[0]")
    private Output<String> salt;

    public Output<String> salt() {
        return this.salt;
    }
    @Export(name="saltedLength", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> saltedLength;

    public Output<Optional<Integer>> saltedLength() {
        return Codegen.optional(this.saltedLength);
    }
    @Export(name="saltedPassword", refs={String.class}, tree="[0]")
    private Output<String> saltedPassword;

    public Output<String> saltedPassword() {
        return this.saltedPassword;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RandomSalt(java.lang.String name) {
        this(name, RandomSaltArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RandomSalt(java.lang.String name, RandomSaltArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RandomSalt(java.lang.String name, RandomSaltArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:RandomSalt", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RandomSalt(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:RandomSalt", name, null, makeResourceOptions(options, id), false);
    }

    private static RandomSaltArgs makeArgs(RandomSaltArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RandomSaltArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RandomSalt get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RandomSalt(name, id, options);
    }
}
