// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.caliban0.pulumicherryservers.Utilities;
import com.caliban0.pulumicherryservers.provider.ServerArgs;
import com.caliban0.pulumicherryservers.provider.outputs.ServerIPState;
import com.caliban0.pulumicherryservers.provider.outputs.ServerPricingState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Cherry Servers server instance.
 * 
 */
@ResourceType(type="pulumi-cherry-servers:provider:Server")
public class Server extends com.pulumi.resources.CustomResource {
    /**
     * Whether re-installation is permitted for this server.
     * 
     */
    @Export(name="allowReinstall", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> allowReinstall;

    /**
     * @return Whether re-installation is permitted for this server.
     * 
     */
    public Output<Optional<Boolean>> allowReinstall() {
        return Codegen.optional(this.allowReinstall);
    }
    /**
     * Whether BGP is enabled for the server.
     * 
     */
    @Export(name="bgp", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> bgp;

    /**
     * @return Whether BGP is enabled for the server.
     * 
     */
    public Output<Optional<Boolean>> bgp() {
        return Codegen.optional(this.bgp);
    }
    /**
     * Server billing cycle.
     * 
     */
    @Export(name="cycle", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cycle;

    /**
     * @return Server billing cycle.
     * 
     */
    public Output<Optional<String>> cycle() {
        return Codegen.optional(this.cycle);
    }
    /**
     * Server discount code.
     * 
     */
    @Export(name="discountCode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> discountCode;

    /**
     * @return Server discount code.
     * 
     */
    public Output<Optional<String>> discountCode() {
        return Codegen.optional(this.discountCode);
    }
    /**
     * IDs of extra IP addresses assigned to the server.
     * 
     */
    @Export(name="extraIPs", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> extraIPs;

    /**
     * @return IDs of extra IP addresses assigned to the server.
     * 
     */
    public Output<Optional<List<String>>> extraIPs() {
        return Codegen.optional(this.extraIPs);
    }
    /**
     * Server hostname.
     * 
     */
    @Export(name="hostname", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> hostname;

    /**
     * @return Server hostname.
     * 
     */
    public Output<Optional<String>> hostname() {
        return Codegen.optional(this.hostname);
    }
    /**
     * Server image slug. Updating requires re-installation.
     * 
     */
    @Export(name="image", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> image;

    /**
     * @return Server image slug. Updating requires re-installation.
     * 
     */
    public Output<Optional<String>> image() {
        return Codegen.optional(this.image);
    }
    /**
     * Server IP addresses.
     * 
     */
    @Export(name="ips", refs={List.class,ServerIPState.class}, tree="[0,1]")
    private Output<List<ServerIPState>> ips;

    /**
     * @return Server IP addresses.
     * 
     */
    public Output<List<ServerIPState>> ips() {
        return this.ips;
    }
    /**
     * Server OS partition size. Updating requires re-installation.
     * 
     */
    @Export(name="osPartitionSize", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> osPartitionSize;

    /**
     * @return Server OS partition size. Updating requires re-installation.
     * 
     */
    public Output<Optional<Integer>> osPartitionSize() {
        return Codegen.optional(this.osPartitionSize);
    }
    /**
     * Server plan slug.
     * 
     */
    @Export(name="plan", refs={String.class}, tree="[0]")
    private Output<String> plan;

    /**
     * @return Server plan slug.
     * 
     */
    public Output<String> plan() {
        return this.plan;
    }
    /**
     * Server pricing.
     * 
     */
    @Export(name="pricing", refs={ServerPricingState.class}, tree="[0]")
    private Output<ServerPricingState> pricing;

    /**
     * @return Server pricing.
     * 
     */
    public Output<ServerPricingState> pricing() {
        return this.pricing;
    }
    /**
     * ID of the server the project belongs to.
     * 
     */
    @Export(name="project", refs={Integer.class}, tree="[0]")
    private Output<Integer> project;

    /**
     * @return ID of the server the project belongs to.
     * 
     */
    public Output<Integer> project() {
        return this.project;
    }
    /**
     * Server region slug.
     * 
     */
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    /**
     * @return Server region slug.
     * 
     */
    public Output<String> region() {
        return this.region;
    }
    /**
     * Whether the server is a spot instance.
     * 
     */
    @Export(name="spot", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> spot;

    /**
     * @return Whether the server is a spot instance.
     * 
     */
    public Output<Optional<Boolean>> spot() {
        return Codegen.optional(this.spot);
    }
    /**
     * Server SSH key IDs. Updating requires re-installation.
     * 
     */
    @Export(name="sshKeys", refs={List.class,Integer.class}, tree="[0,1]")
    private Output</* @Nullable */ List<Integer>> sshKeys;

    /**
     * @return Server SSH key IDs. Updating requires re-installation.
     * 
     */
    public Output<Optional<List<Integer>>> sshKeys() {
        return Codegen.optional(this.sshKeys);
    }
    /**
     * Server status, such as &#39;deploying&#39; or &#39;deployed&#39;.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Server status, such as &#39;deploying&#39; or &#39;deployed&#39;.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Server elastic block storage ID.
     * 
     */
    @Export(name="storage", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> storage;

    /**
     * @return Server elastic block storage ID.
     * 
     */
    public Output<Optional<Integer>> storage() {
        return Codegen.optional(this.storage);
    }
    /**
     * Server tags.
     * 
     */
    @Export(name="tags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> tags;

    /**
     * @return Server tags.
     * 
     */
    public Output<Optional<Map<String,String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * Server user data. Bash or cloud-config script. Updating requires re-installation.
     * 
     */
    @Export(name="userData", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> userData;

    /**
     * @return Server user data. Bash or cloud-config script. Updating requires re-installation.
     * 
     */
    public Output<Optional<String>> userData() {
        return Codegen.optional(this.userData);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Server(java.lang.String name) {
        this(name, ServerArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Server(java.lang.String name, ServerArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Server(java.lang.String name, ServerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:Server", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Server(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumi-cherry-servers:provider:Server", name, null, makeResourceOptions(options, id), false);
    }

    private static ServerArgs makeArgs(ServerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ServerArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Server get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Server(name, id, options);
    }
}
