// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers.provider;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServerArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServerArgs Empty = new ServerArgs();

    /**
     * Whether re-installation is permitted for this server.
     * 
     */
    @Import(name="allowReinstall")
    private @Nullable Output<Boolean> allowReinstall;

    /**
     * @return Whether re-installation is permitted for this server.
     * 
     */
    public Optional<Output<Boolean>> allowReinstall() {
        return Optional.ofNullable(this.allowReinstall);
    }

    /**
     * Whether BGP is enabled for the server.
     * 
     */
    @Import(name="bgp")
    private @Nullable Output<Boolean> bgp;

    /**
     * @return Whether BGP is enabled for the server.
     * 
     */
    public Optional<Output<Boolean>> bgp() {
        return Optional.ofNullable(this.bgp);
    }

    /**
     * Server billing cycle.
     * 
     */
    @Import(name="cycle")
    private @Nullable Output<String> cycle;

    /**
     * @return Server billing cycle.
     * 
     */
    public Optional<Output<String>> cycle() {
        return Optional.ofNullable(this.cycle);
    }

    /**
     * Server discount code.
     * 
     */
    @Import(name="discountCode")
    private @Nullable Output<String> discountCode;

    /**
     * @return Server discount code.
     * 
     */
    public Optional<Output<String>> discountCode() {
        return Optional.ofNullable(this.discountCode);
    }

    /**
     * IDs of extra IP addresses assigned to the server.
     * 
     */
    @Import(name="extraIPs")
    private @Nullable Output<List<String>> extraIPs;

    /**
     * @return IDs of extra IP addresses assigned to the server.
     * 
     */
    public Optional<Output<List<String>>> extraIPs() {
        return Optional.ofNullable(this.extraIPs);
    }

    /**
     * Server hostname.
     * 
     */
    @Import(name="hostname")
    private @Nullable Output<String> hostname;

    /**
     * @return Server hostname.
     * 
     */
    public Optional<Output<String>> hostname() {
        return Optional.ofNullable(this.hostname);
    }

    /**
     * Server image slug. Updating requires re-installation.
     * 
     */
    @Import(name="image")
    private @Nullable Output<String> image;

    /**
     * @return Server image slug. Updating requires re-installation.
     * 
     */
    public Optional<Output<String>> image() {
        return Optional.ofNullable(this.image);
    }

    /**
     * Server name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Server name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Server OS partition size. Updating requires re-installation.
     * 
     */
    @Import(name="osPartitionSize")
    private @Nullable Output<Integer> osPartitionSize;

    /**
     * @return Server OS partition size. Updating requires re-installation.
     * 
     */
    public Optional<Output<Integer>> osPartitionSize() {
        return Optional.ofNullable(this.osPartitionSize);
    }

    /**
     * Server plan slug.
     * 
     */
    @Import(name="plan", required=true)
    private Output<String> plan;

    /**
     * @return Server plan slug.
     * 
     */
    public Output<String> plan() {
        return this.plan;
    }

    /**
     * ID of the server the project belongs to.
     * 
     */
    @Import(name="project", required=true)
    private Output<Integer> project;

    /**
     * @return ID of the server the project belongs to.
     * 
     */
    public Output<Integer> project() {
        return this.project;
    }

    /**
     * Server region slug.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return Server region slug.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    /**
     * Whether the server is a spot instance.
     * 
     */
    @Import(name="spot")
    private @Nullable Output<Boolean> spot;

    /**
     * @return Whether the server is a spot instance.
     * 
     */
    public Optional<Output<Boolean>> spot() {
        return Optional.ofNullable(this.spot);
    }

    /**
     * Server SSH key IDs. Updating requires re-installation.
     * 
     */
    @Import(name="sshKeys")
    private @Nullable Output<List<Integer>> sshKeys;

    /**
     * @return Server SSH key IDs. Updating requires re-installation.
     * 
     */
    public Optional<Output<List<Integer>>> sshKeys() {
        return Optional.ofNullable(this.sshKeys);
    }

    @Import(name="storageID")
    private @Nullable Output<Integer> storageID;

    public Optional<Output<Integer>> storageID() {
        return Optional.ofNullable(this.storageID);
    }

    /**
     * Server tags.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<Map<String,String>> tags;

    /**
     * @return Server tags.
     * 
     */
    public Optional<Output<Map<String,String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    /**
     * Server user data. Bash or cloud-config script. Updating requires re-installation.
     * 
     */
    @Import(name="userData")
    private @Nullable Output<String> userData;

    /**
     * @return Server user data. Bash or cloud-config script. Updating requires re-installation.
     * 
     */
    public Optional<Output<String>> userData() {
        return Optional.ofNullable(this.userData);
    }

    private ServerArgs() {}

    private ServerArgs(ServerArgs $) {
        this.allowReinstall = $.allowReinstall;
        this.bgp = $.bgp;
        this.cycle = $.cycle;
        this.discountCode = $.discountCode;
        this.extraIPs = $.extraIPs;
        this.hostname = $.hostname;
        this.image = $.image;
        this.name = $.name;
        this.osPartitionSize = $.osPartitionSize;
        this.plan = $.plan;
        this.project = $.project;
        this.region = $.region;
        this.spot = $.spot;
        this.sshKeys = $.sshKeys;
        this.storageID = $.storageID;
        this.tags = $.tags;
        this.userData = $.userData;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerArgs $;

        public Builder() {
            $ = new ServerArgs();
        }

        public Builder(ServerArgs defaults) {
            $ = new ServerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param allowReinstall Whether re-installation is permitted for this server.
         * 
         * @return builder
         * 
         */
        public Builder allowReinstall(@Nullable Output<Boolean> allowReinstall) {
            $.allowReinstall = allowReinstall;
            return this;
        }

        /**
         * @param allowReinstall Whether re-installation is permitted for this server.
         * 
         * @return builder
         * 
         */
        public Builder allowReinstall(Boolean allowReinstall) {
            return allowReinstall(Output.of(allowReinstall));
        }

        /**
         * @param bgp Whether BGP is enabled for the server.
         * 
         * @return builder
         * 
         */
        public Builder bgp(@Nullable Output<Boolean> bgp) {
            $.bgp = bgp;
            return this;
        }

        /**
         * @param bgp Whether BGP is enabled for the server.
         * 
         * @return builder
         * 
         */
        public Builder bgp(Boolean bgp) {
            return bgp(Output.of(bgp));
        }

        /**
         * @param cycle Server billing cycle.
         * 
         * @return builder
         * 
         */
        public Builder cycle(@Nullable Output<String> cycle) {
            $.cycle = cycle;
            return this;
        }

        /**
         * @param cycle Server billing cycle.
         * 
         * @return builder
         * 
         */
        public Builder cycle(String cycle) {
            return cycle(Output.of(cycle));
        }

        /**
         * @param discountCode Server discount code.
         * 
         * @return builder
         * 
         */
        public Builder discountCode(@Nullable Output<String> discountCode) {
            $.discountCode = discountCode;
            return this;
        }

        /**
         * @param discountCode Server discount code.
         * 
         * @return builder
         * 
         */
        public Builder discountCode(String discountCode) {
            return discountCode(Output.of(discountCode));
        }

        /**
         * @param extraIPs IDs of extra IP addresses assigned to the server.
         * 
         * @return builder
         * 
         */
        public Builder extraIPs(@Nullable Output<List<String>> extraIPs) {
            $.extraIPs = extraIPs;
            return this;
        }

        /**
         * @param extraIPs IDs of extra IP addresses assigned to the server.
         * 
         * @return builder
         * 
         */
        public Builder extraIPs(List<String> extraIPs) {
            return extraIPs(Output.of(extraIPs));
        }

        /**
         * @param extraIPs IDs of extra IP addresses assigned to the server.
         * 
         * @return builder
         * 
         */
        public Builder extraIPs(String... extraIPs) {
            return extraIPs(List.of(extraIPs));
        }

        /**
         * @param hostname Server hostname.
         * 
         * @return builder
         * 
         */
        public Builder hostname(@Nullable Output<String> hostname) {
            $.hostname = hostname;
            return this;
        }

        /**
         * @param hostname Server hostname.
         * 
         * @return builder
         * 
         */
        public Builder hostname(String hostname) {
            return hostname(Output.of(hostname));
        }

        /**
         * @param image Server image slug. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder image(@Nullable Output<String> image) {
            $.image = image;
            return this;
        }

        /**
         * @param image Server image slug. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder image(String image) {
            return image(Output.of(image));
        }

        /**
         * @param name Server name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Server name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param osPartitionSize Server OS partition size. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder osPartitionSize(@Nullable Output<Integer> osPartitionSize) {
            $.osPartitionSize = osPartitionSize;
            return this;
        }

        /**
         * @param osPartitionSize Server OS partition size. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder osPartitionSize(Integer osPartitionSize) {
            return osPartitionSize(Output.of(osPartitionSize));
        }

        /**
         * @param plan Server plan slug.
         * 
         * @return builder
         * 
         */
        public Builder plan(Output<String> plan) {
            $.plan = plan;
            return this;
        }

        /**
         * @param plan Server plan slug.
         * 
         * @return builder
         * 
         */
        public Builder plan(String plan) {
            return plan(Output.of(plan));
        }

        /**
         * @param project ID of the server the project belongs to.
         * 
         * @return builder
         * 
         */
        public Builder project(Output<Integer> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project ID of the server the project belongs to.
         * 
         * @return builder
         * 
         */
        public Builder project(Integer project) {
            return project(Output.of(project));
        }

        /**
         * @param region Server region slug.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region Server region slug.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param spot Whether the server is a spot instance.
         * 
         * @return builder
         * 
         */
        public Builder spot(@Nullable Output<Boolean> spot) {
            $.spot = spot;
            return this;
        }

        /**
         * @param spot Whether the server is a spot instance.
         * 
         * @return builder
         * 
         */
        public Builder spot(Boolean spot) {
            return spot(Output.of(spot));
        }

        /**
         * @param sshKeys Server SSH key IDs. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder sshKeys(@Nullable Output<List<Integer>> sshKeys) {
            $.sshKeys = sshKeys;
            return this;
        }

        /**
         * @param sshKeys Server SSH key IDs. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder sshKeys(List<Integer> sshKeys) {
            return sshKeys(Output.of(sshKeys));
        }

        /**
         * @param sshKeys Server SSH key IDs. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder sshKeys(Integer... sshKeys) {
            return sshKeys(List.of(sshKeys));
        }

        public Builder storageID(@Nullable Output<Integer> storageID) {
            $.storageID = storageID;
            return this;
        }

        public Builder storageID(Integer storageID) {
            return storageID(Output.of(storageID));
        }

        /**
         * @param tags Server tags.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<Map<String,String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags Server tags.
         * 
         * @return builder
         * 
         */
        public Builder tags(Map<String,String> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param userData Server user data. Bash or cloud-config script. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder userData(@Nullable Output<String> userData) {
            $.userData = userData;
            return this;
        }

        /**
         * @param userData Server user data. Bash or cloud-config script. Updating requires re-installation.
         * 
         * @return builder
         * 
         */
        public Builder userData(String userData) {
            return userData(Output.of(userData));
        }

        public ServerArgs build() {
            if ($.plan == null) {
                throw new MissingRequiredPropertyException("ServerArgs", "plan");
            }
            if ($.project == null) {
                throw new MissingRequiredPropertyException("ServerArgs", "project");
            }
            if ($.region == null) {
                throw new MissingRequiredPropertyException("ServerArgs", "region");
            }
            return $;
        }
    }

}
