// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Caliban0.PulumiCherryServers.Provider
{
    /// <summary>
    /// Cherry Servers IP address.
    /// </summary>
    [PulumiCherryServersResourceType("pulumi-cherry-servers:provider:IP")]
    public partial class IP : global::Pulumi.CustomResource
    {
        /// <summary>
        /// IP address A record.
        /// </summary>
        [Output("aRecord")]
        public Output<string?> ARecord { get; private set; } = null!;

        /// <summary>
        /// Actual address.
        /// </summary>
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        /// <summary>
        /// IP address family.
        /// </summary>
        [Output("addressFamily")]
        public Output<int> AddressFamily { get; private set; } = null!;

        /// <summary>
        /// IP address CIDR.
        /// </summary>
        [Output("cidr")]
        public Output<string> Cidr { get; private set; } = null!;

        [Output("project")]
        public Output<int> Project { get; private set; } = null!;

        /// <summary>
        /// IP address PTR record.
        /// </summary>
        [Output("ptrRecord")]
        public Output<string?> PtrRecord { get; private set; } = null!;

        /// <summary>
        /// IP address project ID.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// IP address that this address is routed to.
        /// </summary>
        [Output("routedTo")]
        public Output<string?> RoutedTo { get; private set; } = null!;

        /// <summary>
        /// IP address tags.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        /// <summary>
        /// Server that this address is targeted to.
        /// </summary>
        [Output("targetedTo")]
        public Output<int?> TargetedTo { get; private set; } = null!;

        /// <summary>
        /// IP address type.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a IP resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IP(string name, IPArgs args, CustomResourceOptions? options = null)
            : base("pulumi-cherry-servers:provider:IP", name, args ?? new IPArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IP(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumi-cherry-servers:provider:IP", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IP resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IP Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new IP(name, id, options);
        }
    }

    public sealed class IPArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// IP address A record.
        /// </summary>
        [Input("aRecord")]
        public Input<string>? ARecord { get; set; }

        [Input("project", required: true)]
        public Input<int> Project { get; set; } = null!;

        /// <summary>
        /// IP address PTR record.
        /// </summary>
        [Input("ptrRecord")]
        public Input<string>? PtrRecord { get; set; }

        /// <summary>
        /// IP address project ID.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// IP address that this address is routed to.
        /// </summary>
        [Input("routedTo")]
        public Input<string>? RoutedTo { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// IP address tags.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Server that this address is targeted to.
        /// </summary>
        [Input("targetedTo")]
        public Input<int>? TargetedTo { get; set; }

        public IPArgs()
        {
        }
        public static new IPArgs Empty => new IPArgs();
    }
}
