// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Caliban0.PulumiCherryServers.Provider
{
    [PulumiCherryServersResourceType("pulumi-cherry-servers:provider:RandomSalt")]
    public partial class RandomSalt : global::Pulumi.CustomResource
    {
        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        [Output("salt")]
        public Output<string> Salt { get; private set; } = null!;

        [Output("saltedLength")]
        public Output<int?> SaltedLength { get; private set; } = null!;

        [Output("saltedPassword")]
        public Output<string> SaltedPassword { get; private set; } = null!;


        /// <summary>
        /// Create a RandomSalt resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RandomSalt(string name, RandomSaltArgs args, CustomResourceOptions? options = null)
            : base("pulumi-cherry-servers:provider:RandomSalt", name, args ?? new RandomSaltArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RandomSalt(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumi-cherry-servers:provider:RandomSalt", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RandomSalt resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RandomSalt Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RandomSalt(name, id, options);
        }
    }

    public sealed class RandomSaltArgs : global::Pulumi.ResourceArgs
    {
        [Input("password", required: true)]
        public Input<string> Password { get; set; } = null!;

        [Input("saltedLength")]
        public Input<int>? SaltedLength { get; set; }

        public RandomSaltArgs()
        {
        }
        public static new RandomSaltArgs Empty => new RandomSaltArgs();
    }
}
