// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Caliban0.PulumiCherryServers.Provider
{
    /// <summary>
    /// Cherry Servers server instance.
    /// </summary>
    [PulumiCherryServersResourceType("pulumi-cherry-servers:provider:Server")]
    public partial class Server : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether re-installation is permitted for this server.
        /// </summary>
        [Output("allowReinstall")]
        public Output<bool?> AllowReinstall { get; private set; } = null!;

        /// <summary>
        /// Whether BGP is enabled for the server.
        /// </summary>
        [Output("bgp")]
        public Output<bool?> Bgp { get; private set; } = null!;

        /// <summary>
        /// Server billing cycle.
        /// </summary>
        [Output("cycle")]
        public Output<string?> Cycle { get; private set; } = null!;

        /// <summary>
        /// Server discount code.
        /// </summary>
        [Output("discountCode")]
        public Output<string?> DiscountCode { get; private set; } = null!;

        /// <summary>
        /// IDs of extra IP addresses assigned to the server.
        /// </summary>
        [Output("extraIPs")]
        public Output<ImmutableArray<string>> ExtraIPs { get; private set; } = null!;

        /// <summary>
        /// Server hostname.
        /// </summary>
        [Output("hostname")]
        public Output<string?> Hostname { get; private set; } = null!;

        /// <summary>
        /// Server image slug. Updating requires re-installation.
        /// </summary>
        [Output("image")]
        public Output<string?> Image { get; private set; } = null!;

        /// <summary>
        /// Server IP addresses.
        /// </summary>
        [Output("ips")]
        public Output<ImmutableArray<Outputs.ServerIPState>> Ips { get; private set; } = null!;

        /// <summary>
        /// Server name.
        /// </summary>
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// Server OS partition size. Updating requires re-installation.
        /// </summary>
        [Output("osPartitionSize")]
        public Output<int?> OsPartitionSize { get; private set; } = null!;

        /// <summary>
        /// Server plan slug.
        /// </summary>
        [Output("plan")]
        public Output<string> Plan { get; private set; } = null!;

        /// <summary>
        /// Server pricing.
        /// </summary>
        [Output("pricing")]
        public Output<Outputs.ServerPricingState> Pricing { get; private set; } = null!;

        /// <summary>
        /// ID of the server the project belongs to.
        /// </summary>
        [Output("project")]
        public Output<int> Project { get; private set; } = null!;

        /// <summary>
        /// Server region slug.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// Whether the server is a spot instance.
        /// </summary>
        [Output("spot")]
        public Output<bool?> Spot { get; private set; } = null!;

        /// <summary>
        /// Server SSH key IDs. Updating requires re-installation.
        /// </summary>
        [Output("sshKeys")]
        public Output<ImmutableArray<int>> SshKeys { get; private set; } = null!;

        /// <summary>
        /// Server status, such as 'deploying' or 'deployed'.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Server elastic block storage ID.
        /// </summary>
        [Output("storage")]
        public Output<int?> Storage { get; private set; } = null!;

        /// <summary>
        /// Server tags.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        /// <summary>
        /// Server user data. Bash or cloud-config script. Updating requires re-installation.
        /// </summary>
        [Output("userData")]
        public Output<string?> UserData { get; private set; } = null!;


        /// <summary>
        /// Create a Server resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Server(string name, ServerArgs args, CustomResourceOptions? options = null)
            : base("pulumi-cherry-servers:provider:Server", name, args ?? new ServerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Server(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumi-cherry-servers:provider:Server", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Server resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Server Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Server(name, id, options);
        }
    }

    public sealed class ServerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether re-installation is permitted for this server.
        /// </summary>
        [Input("allowReinstall")]
        public Input<bool>? AllowReinstall { get; set; }

        /// <summary>
        /// Whether BGP is enabled for the server.
        /// </summary>
        [Input("bgp")]
        public Input<bool>? Bgp { get; set; }

        /// <summary>
        /// Server billing cycle.
        /// </summary>
        [Input("cycle")]
        public Input<string>? Cycle { get; set; }

        /// <summary>
        /// Server discount code.
        /// </summary>
        [Input("discountCode")]
        public Input<string>? DiscountCode { get; set; }

        [Input("extraIPs")]
        private InputList<string>? _extraIPs;

        /// <summary>
        /// IDs of extra IP addresses assigned to the server.
        /// </summary>
        public InputList<string> ExtraIPs
        {
            get => _extraIPs ?? (_extraIPs = new InputList<string>());
            set => _extraIPs = value;
        }

        /// <summary>
        /// Server hostname.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// Server image slug. Updating requires re-installation.
        /// </summary>
        [Input("image")]
        public Input<string>? Image { get; set; }

        /// <summary>
        /// Server name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Server OS partition size. Updating requires re-installation.
        /// </summary>
        [Input("osPartitionSize")]
        public Input<int>? OsPartitionSize { get; set; }

        /// <summary>
        /// Server plan slug.
        /// </summary>
        [Input("plan", required: true)]
        public Input<string> Plan { get; set; } = null!;

        /// <summary>
        /// ID of the server the project belongs to.
        /// </summary>
        [Input("project", required: true)]
        public Input<int> Project { get; set; } = null!;

        /// <summary>
        /// Server region slug.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// Whether the server is a spot instance.
        /// </summary>
        [Input("spot")]
        public Input<bool>? Spot { get; set; }

        [Input("sshKeys")]
        private InputList<int>? _sshKeys;

        /// <summary>
        /// Server SSH key IDs. Updating requires re-installation.
        /// </summary>
        public InputList<int> SshKeys
        {
            get => _sshKeys ?? (_sshKeys = new InputList<int>());
            set => _sshKeys = value;
        }

        /// <summary>
        /// Server elastic block storage ID.
        /// </summary>
        [Input("storage")]
        public Input<int>? Storage { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Server tags.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Server user data. Bash or cloud-config script. Updating requires re-installation.
        /// </summary>
        [Input("userData")]
        public Input<string>? UserData { get; set; }

        public ServerArgs()
        {
        }
        public static new ServerArgs Empty => new ServerArgs();
    }
}
