// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/caliban0/pulumi-cherry-servers/sdk/go/pulumi-cherry-servers/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "pulumi-cherry-servers:provider:Project":
		r = &Project{}
	case "pulumi-cherry-servers:provider:RandomSalt":
		r = &RandomSalt{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"pulumi-cherry-servers",
		"provider",
		&module{version},
	)
}
