// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"context"
	"reflect"

	"errors"
	"github.com/caliban0/pulumi-cherry-servers/sdk/go/pulumi-cherry-servers/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Cherry Servers IP address.
type IP struct {
	pulumi.CustomResourceState

	// IP address A record.
	ARecord pulumi.StringPtrOutput `pulumi:"aRecord"`
	// Actual address.
	Address pulumi.StringOutput `pulumi:"address"`
	// IP address family.
	AddressFamily pulumi.IntOutput `pulumi:"addressFamily"`
	// IP address CIDR.
	Cidr    pulumi.StringOutput `pulumi:"cidr"`
	Project pulumi.IntOutput    `pulumi:"project"`
	// IP address PTR record.
	PtrRecord pulumi.StringPtrOutput `pulumi:"ptrRecord"`
	// IP address project ID.
	Region pulumi.StringOutput `pulumi:"region"`
	// IP address that this address is routed to.
	RoutedTo pulumi.StringPtrOutput `pulumi:"routedTo"`
	// IP address tags.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// Server that this address is targeted to.
	TargetedTo pulumi.IntPtrOutput `pulumi:"targetedTo"`
	// IP address type.
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewIP registers a new resource with the given unique name, arguments, and options.
func NewIP(ctx *pulumi.Context,
	name string, args *IPArgs, opts ...pulumi.ResourceOption) (*IP, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource IP
	err := ctx.RegisterResource("pulumi-cherry-servers:provider:IP", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIP gets an existing IP resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIP(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IPState, opts ...pulumi.ResourceOption) (*IP, error) {
	var resource IP
	err := ctx.ReadResource("pulumi-cherry-servers:provider:IP", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IP resources.
type ipState struct {
}

type IPState struct {
}

func (IPState) ElementType() reflect.Type {
	return reflect.TypeOf((*ipState)(nil)).Elem()
}

type ipArgs struct {
	// IP address A record.
	ARecord *string `pulumi:"aRecord"`
	Project int     `pulumi:"project"`
	// IP address PTR record.
	PtrRecord *string `pulumi:"ptrRecord"`
	// IP address project ID.
	Region string `pulumi:"region"`
	// IP address that this address is routed to.
	RoutedTo *string `pulumi:"routedTo"`
	// IP address tags.
	Tags map[string]string `pulumi:"tags"`
	// Server that this address is targeted to.
	TargetedTo *int `pulumi:"targetedTo"`
}

// The set of arguments for constructing a IP resource.
type IPArgs struct {
	// IP address A record.
	ARecord pulumi.StringPtrInput
	Project pulumi.IntInput
	// IP address PTR record.
	PtrRecord pulumi.StringPtrInput
	// IP address project ID.
	Region pulumi.StringInput
	// IP address that this address is routed to.
	RoutedTo pulumi.StringPtrInput
	// IP address tags.
	Tags pulumi.StringMapInput
	// Server that this address is targeted to.
	TargetedTo pulumi.IntPtrInput
}

func (IPArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ipArgs)(nil)).Elem()
}

type IPInput interface {
	pulumi.Input

	ToIPOutput() IPOutput
	ToIPOutputWithContext(ctx context.Context) IPOutput
}

func (*IP) ElementType() reflect.Type {
	return reflect.TypeOf((**IP)(nil)).Elem()
}

func (i *IP) ToIPOutput() IPOutput {
	return i.ToIPOutputWithContext(context.Background())
}

func (i *IP) ToIPOutputWithContext(ctx context.Context) IPOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IPOutput)
}

// IPArrayInput is an input type that accepts IPArray and IPArrayOutput values.
// You can construct a concrete instance of `IPArrayInput` via:
//
//	IPArray{ IPArgs{...} }
type IPArrayInput interface {
	pulumi.Input

	ToIPArrayOutput() IPArrayOutput
	ToIPArrayOutputWithContext(context.Context) IPArrayOutput
}

type IPArray []IPInput

func (IPArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IP)(nil)).Elem()
}

func (i IPArray) ToIPArrayOutput() IPArrayOutput {
	return i.ToIPArrayOutputWithContext(context.Background())
}

func (i IPArray) ToIPArrayOutputWithContext(ctx context.Context) IPArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IPArrayOutput)
}

// IPMapInput is an input type that accepts IPMap and IPMapOutput values.
// You can construct a concrete instance of `IPMapInput` via:
//
//	IPMap{ "key": IPArgs{...} }
type IPMapInput interface {
	pulumi.Input

	ToIPMapOutput() IPMapOutput
	ToIPMapOutputWithContext(context.Context) IPMapOutput
}

type IPMap map[string]IPInput

func (IPMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IP)(nil)).Elem()
}

func (i IPMap) ToIPMapOutput() IPMapOutput {
	return i.ToIPMapOutputWithContext(context.Background())
}

func (i IPMap) ToIPMapOutputWithContext(ctx context.Context) IPMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IPMapOutput)
}

type IPOutput struct{ *pulumi.OutputState }

func (IPOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IP)(nil)).Elem()
}

func (o IPOutput) ToIPOutput() IPOutput {
	return o
}

func (o IPOutput) ToIPOutputWithContext(ctx context.Context) IPOutput {
	return o
}

// IP address A record.
func (o IPOutput) ARecord() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IP) pulumi.StringPtrOutput { return v.ARecord }).(pulumi.StringPtrOutput)
}

// Actual address.
func (o IPOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *IP) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// IP address family.
func (o IPOutput) AddressFamily() pulumi.IntOutput {
	return o.ApplyT(func(v *IP) pulumi.IntOutput { return v.AddressFamily }).(pulumi.IntOutput)
}

// IP address CIDR.
func (o IPOutput) Cidr() pulumi.StringOutput {
	return o.ApplyT(func(v *IP) pulumi.StringOutput { return v.Cidr }).(pulumi.StringOutput)
}

func (o IPOutput) Project() pulumi.IntOutput {
	return o.ApplyT(func(v *IP) pulumi.IntOutput { return v.Project }).(pulumi.IntOutput)
}

// IP address PTR record.
func (o IPOutput) PtrRecord() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IP) pulumi.StringPtrOutput { return v.PtrRecord }).(pulumi.StringPtrOutput)
}

// IP address project ID.
func (o IPOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *IP) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// IP address that this address is routed to.
func (o IPOutput) RoutedTo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IP) pulumi.StringPtrOutput { return v.RoutedTo }).(pulumi.StringPtrOutput)
}

// IP address tags.
func (o IPOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *IP) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// Server that this address is targeted to.
func (o IPOutput) TargetedTo() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *IP) pulumi.IntPtrOutput { return v.TargetedTo }).(pulumi.IntPtrOutput)
}

// IP address type.
func (o IPOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *IP) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type IPArrayOutput struct{ *pulumi.OutputState }

func (IPArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IP)(nil)).Elem()
}

func (o IPArrayOutput) ToIPArrayOutput() IPArrayOutput {
	return o
}

func (o IPArrayOutput) ToIPArrayOutputWithContext(ctx context.Context) IPArrayOutput {
	return o
}

func (o IPArrayOutput) Index(i pulumi.IntInput) IPOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IP {
		return vs[0].([]*IP)[vs[1].(int)]
	}).(IPOutput)
}

type IPMapOutput struct{ *pulumi.OutputState }

func (IPMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IP)(nil)).Elem()
}

func (o IPMapOutput) ToIPMapOutput() IPMapOutput {
	return o
}

func (o IPMapOutput) ToIPMapOutputWithContext(ctx context.Context) IPMapOutput {
	return o
}

func (o IPMapOutput) MapIndex(k pulumi.StringInput) IPOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IP {
		return vs[0].(map[string]*IP)[vs[1].(string)]
	}).(IPOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IPInput)(nil)).Elem(), &IP{})
	pulumi.RegisterInputType(reflect.TypeOf((*IPArrayInput)(nil)).Elem(), IPArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IPMapInput)(nil)).Elem(), IPMap{})
	pulumi.RegisterOutputType(IPOutput{})
	pulumi.RegisterOutputType(IPArrayOutput{})
	pulumi.RegisterOutputType(IPMapOutput{})
}
