// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"context"
	"reflect"

	"github.com/caliban0/pulumi-cherry-servers/sdk/go/pulumi-cherry-servers/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ProjectBGPState struct {
	// Whether BGP is enabled.
	Enabled bool `pulumi:"enabled"`
	// LocalASN assigned to the project.
	LocalASN int `pulumi:"localASN"`
}

type ProjectBGPStateOutput struct{ *pulumi.OutputState }

func (ProjectBGPStateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectBGPState)(nil)).Elem()
}

func (o ProjectBGPStateOutput) ToProjectBGPStateOutput() ProjectBGPStateOutput {
	return o
}

func (o ProjectBGPStateOutput) ToProjectBGPStateOutputWithContext(ctx context.Context) ProjectBGPStateOutput {
	return o
}

// Whether BGP is enabled.
func (o ProjectBGPStateOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v ProjectBGPState) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// LocalASN assigned to the project.
func (o ProjectBGPStateOutput) LocalASN() pulumi.IntOutput {
	return o.ApplyT(func(v ProjectBGPState) int { return v.LocalASN }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(ProjectBGPStateOutput{})
}
