// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"context"
	"reflect"

	"github.com/caliban0/pulumi-cherry-servers/sdk/go/pulumi-cherry-servers/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ProjectBgpState struct {
	// Whether BGP is enabled.
	Enabled bool `pulumi:"enabled"`
	// LocalASN assigned to the project.
	LocalASN int `pulumi:"localASN"`
}

type ProjectBgpStateOutput struct{ *pulumi.OutputState }

func (ProjectBgpStateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProjectBgpState)(nil)).Elem()
}

func (o ProjectBgpStateOutput) ToProjectBgpStateOutput() ProjectBgpStateOutput {
	return o
}

func (o ProjectBgpStateOutput) ToProjectBgpStateOutputWithContext(ctx context.Context) ProjectBgpStateOutput {
	return o
}

// Whether BGP is enabled.
func (o ProjectBgpStateOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v ProjectBgpState) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// LocalASN assigned to the project.
func (o ProjectBgpStateOutput) LocalASN() pulumi.IntOutput {
	return o.ApplyT(func(v ProjectBgpState) int { return v.LocalASN }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(ProjectBgpStateOutput{})
}
