// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"context"
	"reflect"

	"errors"
	"github.com/caliban0/pulumi-cherry-servers/sdk/go/pulumi-cherry-servers/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Cherry Servers server instance.
type Server struct {
	pulumi.CustomResourceState

	// Whether re-installation is permitted for this server.
	AllowReinstall pulumi.BoolPtrOutput `pulumi:"allowReinstall"`
	// Whether BGP is enabled for the server.
	Bgp pulumi.BoolPtrOutput `pulumi:"bgp"`
	// Server billing cycle.
	Cycle pulumi.StringPtrOutput `pulumi:"cycle"`
	// Server discount code.
	DiscountCode pulumi.StringPtrOutput `pulumi:"discountCode"`
	// IDs of extra IP addresses assigned to the server.
	ExtraIPs pulumi.StringArrayOutput `pulumi:"extraIPs"`
	// Server hostname.
	Hostname pulumi.StringPtrOutput `pulumi:"hostname"`
	// Server image slug. Updating requires re-installation.
	Image pulumi.StringPtrOutput `pulumi:"image"`
	// Server IP addresses.
	Ips ServerIPStateArrayOutput `pulumi:"ips"`
	// Server name.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// Server OS partition size. Updating requires re-installation.
	OsPartitionSize pulumi.IntPtrOutput `pulumi:"osPartitionSize"`
	// Server plan slug.
	Plan pulumi.StringOutput `pulumi:"plan"`
	// Server pricing.
	Pricing ServerPricingStateOutput `pulumi:"pricing"`
	// ID of the server the project belongs to.
	Project pulumi.IntOutput `pulumi:"project"`
	// Server region slug.
	Region pulumi.StringOutput `pulumi:"region"`
	// Whether the server is a spot instance.
	Spot pulumi.BoolPtrOutput `pulumi:"spot"`
	// Server SSH key IDs. Updating requires re-installation.
	SshKeys pulumi.IntArrayOutput `pulumi:"sshKeys"`
	// Server status, such as 'deploying' or 'deployed'.
	Status    pulumi.StringOutput `pulumi:"status"`
	StorageID pulumi.IntPtrOutput `pulumi:"storageID"`
	// Server tags.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// Server user data. Bash or cloud-config script. Updating requires re-installation.
	UserData pulumi.StringPtrOutput `pulumi:"userData"`
}

// NewServer registers a new resource with the given unique name, arguments, and options.
func NewServer(ctx *pulumi.Context,
	name string, args *ServerArgs, opts ...pulumi.ResourceOption) (*Server, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Plan == nil {
		return nil, errors.New("invalid value for required argument 'Plan'")
	}
	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Server
	err := ctx.RegisterResource("pulumi-cherry-servers:provider:Server", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServer gets an existing Server resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerState, opts ...pulumi.ResourceOption) (*Server, error) {
	var resource Server
	err := ctx.ReadResource("pulumi-cherry-servers:provider:Server", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Server resources.
type serverState struct {
}

type ServerState struct {
}

func (ServerState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverState)(nil)).Elem()
}

type serverArgs struct {
	// Whether re-installation is permitted for this server.
	AllowReinstall *bool `pulumi:"allowReinstall"`
	// Whether BGP is enabled for the server.
	Bgp *bool `pulumi:"bgp"`
	// Server billing cycle.
	Cycle *string `pulumi:"cycle"`
	// Server discount code.
	DiscountCode *string `pulumi:"discountCode"`
	// IDs of extra IP addresses assigned to the server.
	ExtraIPs []string `pulumi:"extraIPs"`
	// Server hostname.
	Hostname *string `pulumi:"hostname"`
	// Server image slug. Updating requires re-installation.
	Image *string `pulumi:"image"`
	// Server name.
	Name *string `pulumi:"name"`
	// Server OS partition size. Updating requires re-installation.
	OsPartitionSize *int `pulumi:"osPartitionSize"`
	// Server plan slug.
	Plan string `pulumi:"plan"`
	// ID of the server the project belongs to.
	Project int `pulumi:"project"`
	// Server region slug.
	Region string `pulumi:"region"`
	// Whether the server is a spot instance.
	Spot *bool `pulumi:"spot"`
	// Server SSH key IDs. Updating requires re-installation.
	SshKeys   []int `pulumi:"sshKeys"`
	StorageID *int  `pulumi:"storageID"`
	// Server tags.
	Tags map[string]string `pulumi:"tags"`
	// Server user data. Bash or cloud-config script. Updating requires re-installation.
	UserData *string `pulumi:"userData"`
}

// The set of arguments for constructing a Server resource.
type ServerArgs struct {
	// Whether re-installation is permitted for this server.
	AllowReinstall pulumi.BoolPtrInput
	// Whether BGP is enabled for the server.
	Bgp pulumi.BoolPtrInput
	// Server billing cycle.
	Cycle pulumi.StringPtrInput
	// Server discount code.
	DiscountCode pulumi.StringPtrInput
	// IDs of extra IP addresses assigned to the server.
	ExtraIPs pulumi.StringArrayInput
	// Server hostname.
	Hostname pulumi.StringPtrInput
	// Server image slug. Updating requires re-installation.
	Image pulumi.StringPtrInput
	// Server name.
	Name pulumi.StringPtrInput
	// Server OS partition size. Updating requires re-installation.
	OsPartitionSize pulumi.IntPtrInput
	// Server plan slug.
	Plan pulumi.StringInput
	// ID of the server the project belongs to.
	Project pulumi.IntInput
	// Server region slug.
	Region pulumi.StringInput
	// Whether the server is a spot instance.
	Spot pulumi.BoolPtrInput
	// Server SSH key IDs. Updating requires re-installation.
	SshKeys   pulumi.IntArrayInput
	StorageID pulumi.IntPtrInput
	// Server tags.
	Tags pulumi.StringMapInput
	// Server user data. Bash or cloud-config script. Updating requires re-installation.
	UserData pulumi.StringPtrInput
}

func (ServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverArgs)(nil)).Elem()
}

type ServerInput interface {
	pulumi.Input

	ToServerOutput() ServerOutput
	ToServerOutputWithContext(ctx context.Context) ServerOutput
}

func (*Server) ElementType() reflect.Type {
	return reflect.TypeOf((**Server)(nil)).Elem()
}

func (i *Server) ToServerOutput() ServerOutput {
	return i.ToServerOutputWithContext(context.Background())
}

func (i *Server) ToServerOutputWithContext(ctx context.Context) ServerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerOutput)
}

// ServerArrayInput is an input type that accepts ServerArray and ServerArrayOutput values.
// You can construct a concrete instance of `ServerArrayInput` via:
//
//	ServerArray{ ServerArgs{...} }
type ServerArrayInput interface {
	pulumi.Input

	ToServerArrayOutput() ServerArrayOutput
	ToServerArrayOutputWithContext(context.Context) ServerArrayOutput
}

type ServerArray []ServerInput

func (ServerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Server)(nil)).Elem()
}

func (i ServerArray) ToServerArrayOutput() ServerArrayOutput {
	return i.ToServerArrayOutputWithContext(context.Background())
}

func (i ServerArray) ToServerArrayOutputWithContext(ctx context.Context) ServerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerArrayOutput)
}

// ServerMapInput is an input type that accepts ServerMap and ServerMapOutput values.
// You can construct a concrete instance of `ServerMapInput` via:
//
//	ServerMap{ "key": ServerArgs{...} }
type ServerMapInput interface {
	pulumi.Input

	ToServerMapOutput() ServerMapOutput
	ToServerMapOutputWithContext(context.Context) ServerMapOutput
}

type ServerMap map[string]ServerInput

func (ServerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Server)(nil)).Elem()
}

func (i ServerMap) ToServerMapOutput() ServerMapOutput {
	return i.ToServerMapOutputWithContext(context.Background())
}

func (i ServerMap) ToServerMapOutputWithContext(ctx context.Context) ServerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerMapOutput)
}

type ServerOutput struct{ *pulumi.OutputState }

func (ServerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Server)(nil)).Elem()
}

func (o ServerOutput) ToServerOutput() ServerOutput {
	return o
}

func (o ServerOutput) ToServerOutputWithContext(ctx context.Context) ServerOutput {
	return o
}

// Whether re-installation is permitted for this server.
func (o ServerOutput) AllowReinstall() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.AllowReinstall }).(pulumi.BoolPtrOutput)
}

// Whether BGP is enabled for the server.
func (o ServerOutput) Bgp() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.Bgp }).(pulumi.BoolPtrOutput)
}

// Server billing cycle.
func (o ServerOutput) Cycle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.Cycle }).(pulumi.StringPtrOutput)
}

// Server discount code.
func (o ServerOutput) DiscountCode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.DiscountCode }).(pulumi.StringPtrOutput)
}

// IDs of extra IP addresses assigned to the server.
func (o ServerOutput) ExtraIPs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Server) pulumi.StringArrayOutput { return v.ExtraIPs }).(pulumi.StringArrayOutput)
}

// Server hostname.
func (o ServerOutput) Hostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.Hostname }).(pulumi.StringPtrOutput)
}

// Server image slug. Updating requires re-installation.
func (o ServerOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.Image }).(pulumi.StringPtrOutput)
}

// Server IP addresses.
func (o ServerOutput) Ips() ServerIPStateArrayOutput {
	return o.ApplyT(func(v *Server) ServerIPStateArrayOutput { return v.Ips }).(ServerIPStateArrayOutput)
}

// Server name.
func (o ServerOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// Server OS partition size. Updating requires re-installation.
func (o ServerOutput) OsPartitionSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.IntPtrOutput { return v.OsPartitionSize }).(pulumi.IntPtrOutput)
}

// Server plan slug.
func (o ServerOutput) Plan() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.Plan }).(pulumi.StringOutput)
}

// Server pricing.
func (o ServerOutput) Pricing() ServerPricingStateOutput {
	return o.ApplyT(func(v *Server) ServerPricingStateOutput { return v.Pricing }).(ServerPricingStateOutput)
}

// ID of the server the project belongs to.
func (o ServerOutput) Project() pulumi.IntOutput {
	return o.ApplyT(func(v *Server) pulumi.IntOutput { return v.Project }).(pulumi.IntOutput)
}

// Server region slug.
func (o ServerOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Whether the server is a spot instance.
func (o ServerOutput) Spot() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.Spot }).(pulumi.BoolPtrOutput)
}

// Server SSH key IDs. Updating requires re-installation.
func (o ServerOutput) SshKeys() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *Server) pulumi.IntArrayOutput { return v.SshKeys }).(pulumi.IntArrayOutput)
}

// Server status, such as 'deploying' or 'deployed'.
func (o ServerOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o ServerOutput) StorageID() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.IntPtrOutput { return v.StorageID }).(pulumi.IntPtrOutput)
}

// Server tags.
func (o ServerOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Server) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// Server user data. Bash or cloud-config script. Updating requires re-installation.
func (o ServerOutput) UserData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.UserData }).(pulumi.StringPtrOutput)
}

type ServerArrayOutput struct{ *pulumi.OutputState }

func (ServerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Server)(nil)).Elem()
}

func (o ServerArrayOutput) ToServerArrayOutput() ServerArrayOutput {
	return o
}

func (o ServerArrayOutput) ToServerArrayOutputWithContext(ctx context.Context) ServerArrayOutput {
	return o
}

func (o ServerArrayOutput) Index(i pulumi.IntInput) ServerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Server {
		return vs[0].([]*Server)[vs[1].(int)]
	}).(ServerOutput)
}

type ServerMapOutput struct{ *pulumi.OutputState }

func (ServerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Server)(nil)).Elem()
}

func (o ServerMapOutput) ToServerMapOutput() ServerMapOutput {
	return o
}

func (o ServerMapOutput) ToServerMapOutputWithContext(ctx context.Context) ServerMapOutput {
	return o
}

func (o ServerMapOutput) MapIndex(k pulumi.StringInput) ServerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Server {
		return vs[0].(map[string]*Server)[vs[1].(string)]
	}).(ServerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerInput)(nil)).Elem(), &Server{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerArrayInput)(nil)).Elem(), ServerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerMapInput)(nil)).Elem(), ServerMap{})
	pulumi.RegisterOutputType(ServerOutput{})
	pulumi.RegisterOutputType(ServerArrayOutput{})
	pulumi.RegisterOutputType(ServerMapOutput{})
}
