# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import caliban0_pulumi_cherry_servers.config as __config
    config = __config
    import caliban0_pulumi_cherry_servers.provider as __provider
    provider = __provider
else:
    config = _utilities.lazy_import('caliban0_pulumi_cherry_servers.config')
    provider = _utilities.lazy_import('caliban0_pulumi_cherry_servers.provider')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pulumi-cherry-servers",
  "mod": "provider",
  "fqn": "caliban0_pulumi_cherry_servers.provider",
  "classes": {
   "pulumi-cherry-servers:provider:Project": "Project",
   "pulumi-cherry-servers:provider:RandomSalt": "RandomSalt"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pulumi-cherry-servers",
  "token": "pulumi:providers:pulumi-cherry-servers",
  "fqn": "caliban0_pulumi_cherry_servers",
  "class": "Provider"
 }
]
"""
)
