# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['IPArgs', 'IP']

@pulumi.input_type
class IPArgs:
    def __init__(__self__, *,
                 project: pulumi.Input[_builtins.int],
                 region: pulumi.Input[_builtins.str],
                 a_record: Optional[pulumi.Input[_builtins.str]] = None,
                 ptr_record: Optional[pulumi.Input[_builtins.str]] = None,
                 routed_to: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 targeted_to: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a IP resource.
        :param pulumi.Input[_builtins.str] region: IP address project ID.
        :param pulumi.Input[_builtins.str] a_record: IP address A record.
        :param pulumi.Input[_builtins.str] ptr_record: IP address PTR record.
        :param pulumi.Input[_builtins.str] routed_to: IP address that this address is routed to.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: IP address tags.
        :param pulumi.Input[_builtins.int] targeted_to: Server that this address is targeted to.
        """
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "region", region)
        if a_record is not None:
            pulumi.set(__self__, "a_record", a_record)
        if ptr_record is not None:
            pulumi.set(__self__, "ptr_record", ptr_record)
        if routed_to is not None:
            pulumi.set(__self__, "routed_to", routed_to)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if targeted_to is not None:
            pulumi.set(__self__, "targeted_to", targeted_to)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[_builtins.int]:
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[_builtins.str]:
        """
        IP address project ID.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="aRecord")
    def a_record(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP address A record.
        """
        return pulumi.get(self, "a_record")

    @a_record.setter
    def a_record(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "a_record", value)

    @_builtins.property
    @pulumi.getter(name="ptrRecord")
    def ptr_record(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP address PTR record.
        """
        return pulumi.get(self, "ptr_record")

    @ptr_record.setter
    def ptr_record(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ptr_record", value)

    @_builtins.property
    @pulumi.getter(name="routedTo")
    def routed_to(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP address that this address is routed to.
        """
        return pulumi.get(self, "routed_to")

    @routed_to.setter
    def routed_to(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "routed_to", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        IP address tags.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="targetedTo")
    def targeted_to(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Server that this address is targeted to.
        """
        return pulumi.get(self, "targeted_to")

    @targeted_to.setter
    def targeted_to(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "targeted_to", value)


@pulumi.type_token("pulumi-cherry-servers:provider:IP")
class IP(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 a_record: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.int]] = None,
                 ptr_record: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 routed_to: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 targeted_to: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Cherry Servers IP address.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] a_record: IP address A record.
        :param pulumi.Input[_builtins.str] ptr_record: IP address PTR record.
        :param pulumi.Input[_builtins.str] region: IP address project ID.
        :param pulumi.Input[_builtins.str] routed_to: IP address that this address is routed to.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: IP address tags.
        :param pulumi.Input[_builtins.int] targeted_to: Server that this address is targeted to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IPArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Cherry Servers IP address.

        :param str resource_name: The name of the resource.
        :param IPArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IPArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 a_record: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.int]] = None,
                 ptr_record: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 routed_to: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 targeted_to: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IPArgs.__new__(IPArgs)

            __props__.__dict__["a_record"] = a_record
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            __props__.__dict__["ptr_record"] = ptr_record
            if region is None and not opts.urn:
                raise TypeError("Missing required property 'region'")
            __props__.__dict__["region"] = region
            __props__.__dict__["routed_to"] = routed_to
            __props__.__dict__["tags"] = tags
            __props__.__dict__["targeted_to"] = targeted_to
            __props__.__dict__["address"] = None
            __props__.__dict__["address_family"] = None
            __props__.__dict__["cidr"] = None
            __props__.__dict__["type"] = None
        super(IP, __self__).__init__(
            'pulumi-cherry-servers:provider:IP',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'IP':
        """
        Get an existing IP resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = IPArgs.__new__(IPArgs)

        __props__.__dict__["a_record"] = None
        __props__.__dict__["address"] = None
        __props__.__dict__["address_family"] = None
        __props__.__dict__["cidr"] = None
        __props__.__dict__["project"] = None
        __props__.__dict__["ptr_record"] = None
        __props__.__dict__["region"] = None
        __props__.__dict__["routed_to"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["targeted_to"] = None
        __props__.__dict__["type"] = None
        return IP(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="aRecord")
    def a_record(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        IP address A record.
        """
        return pulumi.get(self, "a_record")

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Output[_builtins.str]:
        """
        Actual address.
        """
        return pulumi.get(self, "address")

    @_builtins.property
    @pulumi.getter(name="addressFamily")
    def address_family(self) -> pulumi.Output[_builtins.int]:
        """
        IP address family.
        """
        return pulumi.get(self, "address_family")

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> pulumi.Output[_builtins.str]:
        """
        IP address CIDR.
        """
        return pulumi.get(self, "cidr")

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter(name="ptrRecord")
    def ptr_record(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        IP address PTR record.
        """
        return pulumi.get(self, "ptr_record")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        IP address project ID.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="routedTo")
    def routed_to(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        IP address that this address is routed to.
        """
        return pulumi.get(self, "routed_to")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        IP address tags.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="targetedTo")
    def targeted_to(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Server that this address is targeted to.
        """
        return pulumi.get(self, "targeted_to")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        IP address type.
        """
        return pulumi.get(self, "type")

