# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'ProjectBgpState',
]

@pulumi.output_type
class ProjectBgpState(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "localASN":
            suggest = "local_asn"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ProjectBgpState. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ProjectBgpState.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ProjectBgpState.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 local_asn: _builtins.int):
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "local_asn", local_asn)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="localASN")
    def local_asn(self) -> _builtins.int:
        return pulumi.get(self, "local_asn")


