# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'ServerIPState',
    'ServerPricingState',
]

@pulumi.output_type
class ServerIPState(dict):
    def __init__(__self__, *,
                 address: _builtins.str,
                 id: _builtins.str,
                 type: _builtins.str):
        pulumi.set(__self__, "address", address)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def address(self) -> _builtins.str:
        return pulumi.get(self, "address")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")


@pulumi.output_type
class ServerPricingState(dict):
    def __init__(__self__, *,
                 currency: _builtins.str,
                 price: _builtins.float,
                 unit: _builtins.str):
        pulumi.set(__self__, "currency", currency)
        pulumi.set(__self__, "price", price)
        pulumi.set(__self__, "unit", unit)

    @_builtins.property
    @pulumi.getter
    def currency(self) -> _builtins.str:
        return pulumi.get(self, "currency")

    @_builtins.property
    @pulumi.getter
    def price(self) -> _builtins.float:
        return pulumi.get(self, "price")

    @_builtins.property
    @pulumi.getter
    def unit(self) -> _builtins.str:
        return pulumi.get(self, "unit")


