# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['RandomSaltArgs', 'RandomSalt']

@pulumi.input_type
class RandomSaltArgs:
    def __init__(__self__, *,
                 password: pulumi.Input[_builtins.str],
                 salted_length: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a RandomSalt resource.
        """
        pulumi.set(__self__, "password", password)
        if salted_length is not None:
            pulumi.set(__self__, "salted_length", salted_length)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="saltedLength")
    def salted_length(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "salted_length")

    @salted_length.setter
    def salted_length(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "salted_length", value)


@pulumi.type_token("pulumi-cherry-servers:provider:RandomSalt")
class RandomSalt(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 salted_length: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Create a RandomSalt resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RandomSaltArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RandomSalt resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param RandomSaltArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RandomSaltArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 salted_length: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RandomSaltArgs.__new__(RandomSaltArgs)

            if password is None and not opts.urn:
                raise TypeError("Missing required property 'password'")
            __props__.__dict__["password"] = password
            __props__.__dict__["salted_length"] = salted_length
            __props__.__dict__["salt"] = None
            __props__.__dict__["salted_password"] = None
        super(RandomSalt, __self__).__init__(
            'pulumi-cherry-servers:provider:RandomSalt',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'RandomSalt':
        """
        Get an existing RandomSalt resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = RandomSaltArgs.__new__(RandomSaltArgs)

        __props__.__dict__["password"] = None
        __props__.__dict__["salt"] = None
        __props__.__dict__["salted_length"] = None
        __props__.__dict__["salted_password"] = None
        return RandomSalt(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def salt(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "salt")

    @_builtins.property
    @pulumi.getter(name="saltedLength")
    def salted_length(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "salted_length")

    @_builtins.property
    @pulumi.getter(name="saltedPassword")
    def salted_password(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "salted_password")

