# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = ['ServerArgs', 'Server']

@pulumi.input_type
class ServerArgs:
    def __init__(__self__, *,
                 plan: pulumi.Input[_builtins.str],
                 project: pulumi.Input[_builtins.int],
                 region: pulumi.Input[_builtins.str],
                 allow_reinstall: Optional[pulumi.Input[_builtins.bool]] = None,
                 bgp: Optional[pulumi.Input[_builtins.bool]] = None,
                 cycle: Optional[pulumi.Input[_builtins.str]] = None,
                 discount_code: Optional[pulumi.Input[_builtins.str]] = None,
                 extra_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 image: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 os_partition_size: Optional[pulumi.Input[_builtins.int]] = None,
                 spot: Optional[pulumi.Input[_builtins.bool]] = None,
                 ssh_keys: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 storage_id: Optional[pulumi.Input[_builtins.int]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 user_data: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Server resource.
        :param pulumi.Input[_builtins.str] plan: Server plan slug.
        :param pulumi.Input[_builtins.int] project: ID of the server the project belongs to.
        :param pulumi.Input[_builtins.str] region: Server region slug.
        :param pulumi.Input[_builtins.bool] allow_reinstall: Whether re-installation is permitted for this server.
        :param pulumi.Input[_builtins.bool] bgp: Whether BGP is enabled for the server.
        :param pulumi.Input[_builtins.str] cycle: Server billing cycle.
        :param pulumi.Input[_builtins.str] discount_code: Server discount code.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] extra_ips: IDs of extra IP addresses assigned to the server.
        :param pulumi.Input[_builtins.str] hostname: Server hostname.
        :param pulumi.Input[_builtins.str] image: Server image slug. Updating requires re-installation.
        :param pulumi.Input[_builtins.str] name: Server name.
        :param pulumi.Input[_builtins.int] os_partition_size: Server OS partition size. Updating requires re-installation.
        :param pulumi.Input[_builtins.bool] spot: Whether the server is a spot instance.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] ssh_keys: Server SSH key IDs. Updating requires re-installation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Server tags.
        :param pulumi.Input[_builtins.str] user_data: Server user data. Bash or cloud-config script. Updating requires re-installation.
        """
        pulumi.set(__self__, "plan", plan)
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "region", region)
        if allow_reinstall is not None:
            pulumi.set(__self__, "allow_reinstall", allow_reinstall)
        if bgp is not None:
            pulumi.set(__self__, "bgp", bgp)
        if cycle is not None:
            pulumi.set(__self__, "cycle", cycle)
        if discount_code is not None:
            pulumi.set(__self__, "discount_code", discount_code)
        if extra_ips is not None:
            pulumi.set(__self__, "extra_ips", extra_ips)
        if hostname is not None:
            pulumi.set(__self__, "hostname", hostname)
        if image is not None:
            pulumi.set(__self__, "image", image)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if os_partition_size is not None:
            pulumi.set(__self__, "os_partition_size", os_partition_size)
        if spot is not None:
            pulumi.set(__self__, "spot", spot)
        if ssh_keys is not None:
            pulumi.set(__self__, "ssh_keys", ssh_keys)
        if storage_id is not None:
            pulumi.set(__self__, "storage_id", storage_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if user_data is not None:
            pulumi.set(__self__, "user_data", user_data)

    @_builtins.property
    @pulumi.getter
    def plan(self) -> pulumi.Input[_builtins.str]:
        """
        Server plan slug.
        """
        return pulumi.get(self, "plan")

    @plan.setter
    def plan(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "plan", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[_builtins.int]:
        """
        ID of the server the project belongs to.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[_builtins.str]:
        """
        Server region slug.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="allowReinstall")
    def allow_reinstall(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether re-installation is permitted for this server.
        """
        return pulumi.get(self, "allow_reinstall")

    @allow_reinstall.setter
    def allow_reinstall(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_reinstall", value)

    @_builtins.property
    @pulumi.getter
    def bgp(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether BGP is enabled for the server.
        """
        return pulumi.get(self, "bgp")

    @bgp.setter
    def bgp(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "bgp", value)

    @_builtins.property
    @pulumi.getter
    def cycle(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Server billing cycle.
        """
        return pulumi.get(self, "cycle")

    @cycle.setter
    def cycle(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cycle", value)

    @_builtins.property
    @pulumi.getter(name="discountCode")
    def discount_code(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Server discount code.
        """
        return pulumi.get(self, "discount_code")

    @discount_code.setter
    def discount_code(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "discount_code", value)

    @_builtins.property
    @pulumi.getter(name="extraIPs")
    def extra_ips(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of extra IP addresses assigned to the server.
        """
        return pulumi.get(self, "extra_ips")

    @extra_ips.setter
    def extra_ips(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "extra_ips", value)

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Server hostname.
        """
        return pulumi.get(self, "hostname")

    @hostname.setter
    def hostname(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hostname", value)

    @_builtins.property
    @pulumi.getter
    def image(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Server image slug. Updating requires re-installation.
        """
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "image", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Server name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="osPartitionSize")
    def os_partition_size(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Server OS partition size. Updating requires re-installation.
        """
        return pulumi.get(self, "os_partition_size")

    @os_partition_size.setter
    def os_partition_size(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "os_partition_size", value)

    @_builtins.property
    @pulumi.getter
    def spot(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the server is a spot instance.
        """
        return pulumi.get(self, "spot")

    @spot.setter
    def spot(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "spot", value)

    @_builtins.property
    @pulumi.getter(name="sshKeys")
    def ssh_keys(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]:
        """
        Server SSH key IDs. Updating requires re-installation.
        """
        return pulumi.get(self, "ssh_keys")

    @ssh_keys.setter
    def ssh_keys(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]]):
        pulumi.set(self, "ssh_keys", value)

    @_builtins.property
    @pulumi.getter(name="storageID")
    def storage_id(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "storage_id")

    @storage_id.setter
    def storage_id(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "storage_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Server tags.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="userData")
    def user_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Server user data. Bash or cloud-config script. Updating requires re-installation.
        """
        return pulumi.get(self, "user_data")

    @user_data.setter
    def user_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "user_data", value)


@pulumi.type_token("pulumi-cherry-servers:provider:Server")
class Server(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_reinstall: Optional[pulumi.Input[_builtins.bool]] = None,
                 bgp: Optional[pulumi.Input[_builtins.bool]] = None,
                 cycle: Optional[pulumi.Input[_builtins.str]] = None,
                 discount_code: Optional[pulumi.Input[_builtins.str]] = None,
                 extra_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 image: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 os_partition_size: Optional[pulumi.Input[_builtins.int]] = None,
                 plan: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.int]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 spot: Optional[pulumi.Input[_builtins.bool]] = None,
                 ssh_keys: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 storage_id: Optional[pulumi.Input[_builtins.int]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 user_data: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Cherry Servers server instance.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_reinstall: Whether re-installation is permitted for this server.
        :param pulumi.Input[_builtins.bool] bgp: Whether BGP is enabled for the server.
        :param pulumi.Input[_builtins.str] cycle: Server billing cycle.
        :param pulumi.Input[_builtins.str] discount_code: Server discount code.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] extra_ips: IDs of extra IP addresses assigned to the server.
        :param pulumi.Input[_builtins.str] hostname: Server hostname.
        :param pulumi.Input[_builtins.str] image: Server image slug. Updating requires re-installation.
        :param pulumi.Input[_builtins.str] name: Server name.
        :param pulumi.Input[_builtins.int] os_partition_size: Server OS partition size. Updating requires re-installation.
        :param pulumi.Input[_builtins.str] plan: Server plan slug.
        :param pulumi.Input[_builtins.int] project: ID of the server the project belongs to.
        :param pulumi.Input[_builtins.str] region: Server region slug.
        :param pulumi.Input[_builtins.bool] spot: Whether the server is a spot instance.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.int]]] ssh_keys: Server SSH key IDs. Updating requires re-installation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Server tags.
        :param pulumi.Input[_builtins.str] user_data: Server user data. Bash or cloud-config script. Updating requires re-installation.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Cherry Servers server instance.

        :param str resource_name: The name of the resource.
        :param ServerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_reinstall: Optional[pulumi.Input[_builtins.bool]] = None,
                 bgp: Optional[pulumi.Input[_builtins.bool]] = None,
                 cycle: Optional[pulumi.Input[_builtins.str]] = None,
                 discount_code: Optional[pulumi.Input[_builtins.str]] = None,
                 extra_ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 image: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 os_partition_size: Optional[pulumi.Input[_builtins.int]] = None,
                 plan: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.int]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 spot: Optional[pulumi.Input[_builtins.bool]] = None,
                 ssh_keys: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.int]]]] = None,
                 storage_id: Optional[pulumi.Input[_builtins.int]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 user_data: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServerArgs.__new__(ServerArgs)

            __props__.__dict__["allow_reinstall"] = allow_reinstall
            __props__.__dict__["bgp"] = bgp
            __props__.__dict__["cycle"] = cycle
            __props__.__dict__["discount_code"] = discount_code
            __props__.__dict__["extra_ips"] = extra_ips
            __props__.__dict__["hostname"] = hostname
            __props__.__dict__["image"] = image
            __props__.__dict__["name"] = name
            __props__.__dict__["os_partition_size"] = os_partition_size
            if plan is None and not opts.urn:
                raise TypeError("Missing required property 'plan'")
            __props__.__dict__["plan"] = plan
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            if region is None and not opts.urn:
                raise TypeError("Missing required property 'region'")
            __props__.__dict__["region"] = region
            __props__.__dict__["spot"] = spot
            __props__.__dict__["ssh_keys"] = ssh_keys
            __props__.__dict__["storage_id"] = storage_id
            __props__.__dict__["tags"] = tags
            __props__.__dict__["user_data"] = user_data
            __props__.__dict__["ips"] = None
            __props__.__dict__["pricing"] = None
            __props__.__dict__["status"] = None
        super(Server, __self__).__init__(
            'pulumi-cherry-servers:provider:Server',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Server':
        """
        Get an existing Server resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ServerArgs.__new__(ServerArgs)

        __props__.__dict__["allow_reinstall"] = None
        __props__.__dict__["bgp"] = None
        __props__.__dict__["cycle"] = None
        __props__.__dict__["discount_code"] = None
        __props__.__dict__["extra_ips"] = None
        __props__.__dict__["hostname"] = None
        __props__.__dict__["image"] = None
        __props__.__dict__["ips"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["os_partition_size"] = None
        __props__.__dict__["plan"] = None
        __props__.__dict__["pricing"] = None
        __props__.__dict__["project"] = None
        __props__.__dict__["region"] = None
        __props__.__dict__["spot"] = None
        __props__.__dict__["ssh_keys"] = None
        __props__.__dict__["status"] = None
        __props__.__dict__["storage_id"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["user_data"] = None
        return Server(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowReinstall")
    def allow_reinstall(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether re-installation is permitted for this server.
        """
        return pulumi.get(self, "allow_reinstall")

    @_builtins.property
    @pulumi.getter
    def bgp(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether BGP is enabled for the server.
        """
        return pulumi.get(self, "bgp")

    @_builtins.property
    @pulumi.getter
    def cycle(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Server billing cycle.
        """
        return pulumi.get(self, "cycle")

    @_builtins.property
    @pulumi.getter(name="discountCode")
    def discount_code(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Server discount code.
        """
        return pulumi.get(self, "discount_code")

    @_builtins.property
    @pulumi.getter(name="extraIPs")
    def extra_ips(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        IDs of extra IP addresses assigned to the server.
        """
        return pulumi.get(self, "extra_ips")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Server hostname.
        """
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Server image slug. Updating requires re-installation.
        """
        return pulumi.get(self, "image")

    @_builtins.property
    @pulumi.getter
    def ips(self) -> pulumi.Output[Sequence['outputs.ServerIPState']]:
        """
        Server IP addresses.
        """
        return pulumi.get(self, "ips")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Server name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="osPartitionSize")
    def os_partition_size(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Server OS partition size. Updating requires re-installation.
        """
        return pulumi.get(self, "os_partition_size")

    @_builtins.property
    @pulumi.getter
    def plan(self) -> pulumi.Output[_builtins.str]:
        """
        Server plan slug.
        """
        return pulumi.get(self, "plan")

    @_builtins.property
    @pulumi.getter
    def pricing(self) -> pulumi.Output['outputs.ServerPricingState']:
        """
        Server pricing.
        """
        return pulumi.get(self, "pricing")

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.int]:
        """
        ID of the server the project belongs to.
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        Server region slug.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def spot(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the server is a spot instance.
        """
        return pulumi.get(self, "spot")

    @_builtins.property
    @pulumi.getter(name="sshKeys")
    def ssh_keys(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        """
        Server SSH key IDs. Updating requires re-installation.
        """
        return pulumi.get(self, "ssh_keys")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Server status, such as 'deploying' or 'deployed'.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="storageID")
    def storage_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "storage_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Server tags.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="userData")
    def user_data(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Server user data. Bash or cloud-config script. Updating requires re-installation.
        """
        return pulumi.get(self, "user_data")

