// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace provider {
    export interface ServerIPState {
        address: string;
        id: string;
        type: string;
    }

    export interface ServerPricingState {
        currency: string;
        price: number;
        unit: string;
    }

}
