// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.caliban0.pulumicherryservers;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("pulumi-cherry-servers");
/**
 * Cherry Servers API token.
 * 
 */
    public String token() {
        return Codegen.stringProp("token").config(config).require();
    }
}
