// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/caliban0/pulumi-cherry-servers/sdk/go/pulumi-cherry-servers/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Cherry Servers API token.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "pulumi-cherry-servers:token")
}
