// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Caliban0.PulumiCherryServers.Provider.Outputs
{

    [OutputType]
    public sealed class ServerIPState
    {
        public readonly string Address;
        public readonly string Id;
        public readonly string Type;

        [OutputConstructor]
        private ServerIPState(
            string address,

            string id,

            string type)
        {
            Address = address;
            Id = id;
            Type = type;
        }
    }
}
