// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Caliban0.PulumiCherryServers.Provider.Outputs
{

    [OutputType]
    public sealed class ServerPricingState
    {
        public readonly string Currency;
        public readonly double Price;
        public readonly string Unit;

        [OutputConstructor]
        private ServerPricingState(
            string currency,

            double price,

            string unit)
        {
            Currency = currency;
            Price = price;
            Unit = unit;
        }
    }
}
