// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Cherry Servers IP address.
 */
export class IP extends pulumi.CustomResource {
    /**
     * Get an existing IP resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): IP {
        return new IP(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pulumi-cherry-servers:provider:IP';

    /**
     * Returns true if the given object is an instance of IP.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IP {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IP.__pulumiType;
    }

    /**
     * IP address A record.
     */
    declare public readonly aRecord: pulumi.Output<string | undefined>;
    /**
     * Actual address.
     */
    declare public /*out*/ readonly address: pulumi.Output<string>;
    /**
     * IP address family.
     */
    declare public /*out*/ readonly addressFamily: pulumi.Output<number>;
    /**
     * IP address CIDR.
     */
    declare public /*out*/ readonly cidr: pulumi.Output<string>;
    declare public readonly project: pulumi.Output<number>;
    /**
     * IP address PTR record.
     */
    declare public readonly ptrRecord: pulumi.Output<string | undefined>;
    /**
     * IP address project ID.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * IP address that this address is routed to.
     */
    declare public readonly routedTo: pulumi.Output<string | undefined>;
    /**
     * IP address tags.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Server that this address is targeted to.
     */
    declare public readonly targetedTo: pulumi.Output<number | undefined>;
    /**
     * IP address type.
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;

    /**
     * Create a IP resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IPArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["aRecord"] = args?.aRecord;
            resourceInputs["project"] = args?.project;
            resourceInputs["ptrRecord"] = args?.ptrRecord;
            resourceInputs["region"] = args?.region;
            resourceInputs["routedTo"] = args?.routedTo;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["targetedTo"] = args?.targetedTo;
            resourceInputs["address"] = undefined /*out*/;
            resourceInputs["addressFamily"] = undefined /*out*/;
            resourceInputs["cidr"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        } else {
            resourceInputs["aRecord"] = undefined /*out*/;
            resourceInputs["address"] = undefined /*out*/;
            resourceInputs["addressFamily"] = undefined /*out*/;
            resourceInputs["cidr"] = undefined /*out*/;
            resourceInputs["project"] = undefined /*out*/;
            resourceInputs["ptrRecord"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["routedTo"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["targetedTo"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IP.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a IP resource.
 */
export interface IPArgs {
    /**
     * IP address A record.
     */
    aRecord?: pulumi.Input<string>;
    project: pulumi.Input<number>;
    /**
     * IP address PTR record.
     */
    ptrRecord?: pulumi.Input<string>;
    /**
     * IP address project ID.
     */
    region: pulumi.Input<string>;
    /**
     * IP address that this address is routed to.
     */
    routedTo?: pulumi.Input<string>;
    /**
     * IP address tags.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Server that this address is targeted to.
     */
    targetedTo?: pulumi.Input<number>;
}
