// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class RandomSalt extends pulumi.CustomResource {
    /**
     * Get an existing RandomSalt resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RandomSalt {
        return new RandomSalt(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pulumi-cherry-servers:provider:RandomSalt';

    /**
     * Returns true if the given object is an instance of RandomSalt.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RandomSalt {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RandomSalt.__pulumiType;
    }

    declare public readonly password: pulumi.Output<string>;
    declare public /*out*/ readonly salt: pulumi.Output<string>;
    declare public readonly saltedLength: pulumi.Output<number | undefined>;
    declare public /*out*/ readonly saltedPassword: pulumi.Output<string>;

    /**
     * Create a RandomSalt resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RandomSaltArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            resourceInputs["password"] = args?.password;
            resourceInputs["saltedLength"] = args?.saltedLength;
            resourceInputs["salt"] = undefined /*out*/;
            resourceInputs["saltedPassword"] = undefined /*out*/;
        } else {
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["salt"] = undefined /*out*/;
            resourceInputs["saltedLength"] = undefined /*out*/;
            resourceInputs["saltedPassword"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RandomSalt.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RandomSalt resource.
 */
export interface RandomSaltArgs {
    password: pulumi.Input<string>;
    saltedLength?: pulumi.Input<number>;
}
