// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Cherry Servers server instance.
 */
export class Server extends pulumi.CustomResource {
    /**
     * Get an existing Server resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Server {
        return new Server(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pulumi-cherry-servers:provider:Server';

    /**
     * Returns true if the given object is an instance of Server.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Server {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Server.__pulumiType;
    }

    /**
     * Whether re-installation is permitted for this server.
     */
    declare public readonly allowReinstall: pulumi.Output<boolean | undefined>;
    /**
     * Whether BGP is enabled for the server.
     */
    declare public readonly bgp: pulumi.Output<boolean | undefined>;
    /**
     * Server elastic block storage ID.
     */
    declare public readonly blockStorageID: pulumi.Output<number | undefined>;
    /**
     * Server billing cycle.
     */
    declare public readonly cycle: pulumi.Output<string | undefined>;
    /**
     * Server discount code.
     */
    declare public readonly discountCode: pulumi.Output<string | undefined>;
    /**
     * IDs of extra IP addresses assigned to the server.
     */
    declare public readonly extraIPIDs: pulumi.Output<string[] | undefined>;
    /**
     * Server hostname.
     */
    declare public readonly hostname: pulumi.Output<string | undefined>;
    /**
     * Server image slug. Updating requires re-installation.
     */
    declare public readonly image: pulumi.Output<string | undefined>;
    /**
     * Server IP addresses.
     */
    declare public /*out*/ readonly ips: pulumi.Output<outputs.provider.ServerIPState[]>;
    /**
     * Server plan slug.
     */
    declare public readonly plan: pulumi.Output<string>;
    /**
     * Server pricing.
     */
    declare public /*out*/ readonly pricing: pulumi.Output<outputs.provider.ServerPricingState>;
    /**
     * ID of the server the project belongs to.
     */
    declare public readonly projectID: pulumi.Output<number>;
    /**
     * Server region slug.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * Whether the server is a spot instance.
     */
    declare public readonly spot: pulumi.Output<boolean | undefined>;
    /**
     * Server SSH key IDs. Updating requires re-installation.
     */
    declare public readonly sshKeyIDs: pulumi.Output<number[] | undefined>;
    /**
     * Server tags.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Server user data. Bash or cloud-config script. Updating requires re-installation.
     */
    declare public readonly userData: pulumi.Output<string | undefined>;

    /**
     * Create a Server resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.plan === undefined && !opts.urn) {
                throw new Error("Missing required property 'plan'");
            }
            if (args?.projectID === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectID'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["allowReinstall"] = args?.allowReinstall;
            resourceInputs["bgp"] = args?.bgp;
            resourceInputs["blockStorageID"] = args?.blockStorageID;
            resourceInputs["cycle"] = args?.cycle;
            resourceInputs["discountCode"] = args?.discountCode;
            resourceInputs["extraIPIDs"] = args?.extraIPIDs;
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["image"] = args?.image;
            resourceInputs["plan"] = args?.plan;
            resourceInputs["projectID"] = args?.projectID;
            resourceInputs["region"] = args?.region;
            resourceInputs["spot"] = args?.spot;
            resourceInputs["sshKeyIDs"] = args?.sshKeyIDs;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["userData"] = args?.userData;
            resourceInputs["ips"] = undefined /*out*/;
            resourceInputs["pricing"] = undefined /*out*/;
        } else {
            resourceInputs["allowReinstall"] = undefined /*out*/;
            resourceInputs["bgp"] = undefined /*out*/;
            resourceInputs["blockStorageID"] = undefined /*out*/;
            resourceInputs["cycle"] = undefined /*out*/;
            resourceInputs["discountCode"] = undefined /*out*/;
            resourceInputs["extraIPIDs"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["ips"] = undefined /*out*/;
            resourceInputs["plan"] = undefined /*out*/;
            resourceInputs["pricing"] = undefined /*out*/;
            resourceInputs["projectID"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["spot"] = undefined /*out*/;
            resourceInputs["sshKeyIDs"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["userData"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Server.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Server resource.
 */
export interface ServerArgs {
    /**
     * Whether re-installation is permitted for this server.
     */
    allowReinstall?: pulumi.Input<boolean>;
    /**
     * Whether BGP is enabled for the server.
     */
    bgp?: pulumi.Input<boolean>;
    /**
     * Server elastic block storage ID.
     */
    blockStorageID?: pulumi.Input<number>;
    /**
     * Server billing cycle.
     */
    cycle?: pulumi.Input<string>;
    /**
     * Server discount code.
     */
    discountCode?: pulumi.Input<string>;
    /**
     * IDs of extra IP addresses assigned to the server.
     */
    extraIPIDs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Server hostname.
     */
    hostname?: pulumi.Input<string>;
    /**
     * Server image slug. Updating requires re-installation.
     */
    image?: pulumi.Input<string>;
    /**
     * Server plan slug.
     */
    plan: pulumi.Input<string>;
    /**
     * ID of the server the project belongs to.
     */
    projectID: pulumi.Input<number>;
    /**
     * Server region slug.
     */
    region: pulumi.Input<string>;
    /**
     * Whether the server is a spot instance.
     */
    spot?: pulumi.Input<boolean>;
    /**
     * Server SSH key IDs. Updating requires re-installation.
     */
    sshKeyIDs?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Server tags.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Server user data. Bash or cloud-config script. Updating requires re-installation.
     */
    userData?: pulumi.Input<string>;
}
